"""
Utility helpers: story file parsing and Python source code generation.
"""
from __future__ import annotations

import json
import re
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List
import logging

logger = logging.getLogger(__name__)


# ── Story Parser ──────────────────────────────────────────────────────────────

class StoryParser:
    """Reads user story files (.json or .txt/.md) into a normalized dict."""

    REQUIRED_FIELDS = {"id", "title", "steps"}

    def parse_story_file(self, path: str) -> Dict[str, Any]:
        file_path = Path(path)
        if not file_path.exists():
            raise FileNotFoundError(f"Story file not found: {path}")

        suffix = file_path.suffix.lower()
        if suffix == ".json":
            return self._parse_json(file_path)
        if suffix in (".txt", ".md"):
            return self._parse_text(file_path)
        raise ValueError(f"Unsupported story file format: {suffix!r}")

    def _parse_json(self, path: Path) -> Dict[str, Any]:
        with open(path, encoding="utf-8") as f:
            data = json.load(f)
        self._validate(data, path)
        return data

    def _parse_text(self, path: Path) -> Dict[str, Any]:
        lines = [ln.strip() for ln in path.read_text(encoding="utf-8").splitlines() if ln.strip()]
        story: Dict[str, Any] = {
            "id": path.stem,
            "title": lines[0] if lines else "Untitled Story",
            "description": "",
            "steps": [],
            "tags": [],
        }
        counter = 1
        for line in lines[1:]:
            low = line.lower()
            if low.startswith(("given ", "when ", "then ", "and ")):
                _, _, desc = line.partition(" ")
                story["steps"].append({
                    "id": f"step_{counter:02d}",
                    "action": _infer_action(desc),
                    "target": "",
                    "value": "",
                    "description": line,
                })
                counter += 1
            elif not story["description"]:
                story["description"] = line
        return story

    def _validate(self, data: Dict, path: Path) -> None:
        missing = self.REQUIRED_FIELDS - set(data)
        if missing:
            raise ValueError(f"{path.name}: missing required fields {missing}")


# ── Code Generator ────────────────────────────────────────────────────────────

class CodeGenerator:
    """Generates production-ready Page Object and pytest test source from story data."""

    def generate_page_class(self, page_name: str, url: str) -> str:
        snake = _camel_to_snake(page_name)
        path = _url_path(url)
        ts = _timestamp()

        lines = [
            f'"""',
            f"Generated by AI Automation Framework  |  {ts}",
            f"Page  : {page_name}",
            f"URL   : {url}",
            f'"""',
            "from __future__ import annotations",
            "",
            "from playwright.sync_api import Page",
            "",
            "from core.base_page import BasePage",
            f"from locators.{snake}_locators import {page_name}Locators",
            "",
            "",
            f"class {page_name}(BasePage):",
            f'    """Page Object for {page_name}."""',
            "",
            f'    URL_PATH: str = "{path}"',
            "",
            "    def __init__(self, page: Page, base_url: str = \"\") -> None:",
            "        super().__init__(page, base_url)",
            "",
            "    # ── Navigation ────────────────────────────────────────────────────",
            "",
            "    def navigate_to(self) -> None:",
            "        self.navigate(self.URL_PATH)",
            "",
            "    # ── Actions ───────────────────────────────────────────────────────",
            "",
            "    def click_primary_action(self) -> None:",
            f"        self.click({page_name}Locators.PRIMARY_ACTION)",
            "",
            "    def fill_primary_input(self, value: str) -> None:",
            f"        self.fill({page_name}Locators.PRIMARY_INPUT, value)",
            "",
            "    # ── Assertions ────────────────────────────────────────────────────",
            "",
            "    def is_loaded(self) -> bool:",
            f"        return self.is_visible({page_name}Locators.PAGE_INDICATOR)",
            "",
            "    def get_heading(self) -> str:",
            f"        return self.get_text({page_name}Locators.PAGE_HEADING)",
            "",
        ]
        return "\n".join(lines)

    def generate_locator_class(self, page_name: str) -> str:
        ts = _timestamp()

        lines = [
            f'"""',
            f"Generated by AI Automation Framework  |  {ts}",
            f"Locators for: {page_name}",
            "Update selectors after running inspect_current_dom via the MCP server.",
            f'"""',
            "",
            "",
            f"class {page_name}Locators:",
            f'    """CSS/XPath selectors for {page_name}. Update after DOM inspection."""',
            "",
            "    # Page structural indicators",
            "    PAGE_INDICATOR: str = \"main, [role='main'], #main-content\"",
            "    PAGE_HEADING: str = \"h1\"",
            "",
            "    # Primary interactive elements (update after DOM inspection)",
            "    PRIMARY_ACTION: str = \"button[type='submit'], .btn-primary\"",
            "    PRIMARY_INPUT: str = \"input:not([type='hidden'])\"",
            "",
            "    # Status / feedback",
            "    SUCCESS_MESSAGE: str = \"[role='alert'].success, .alert-success\"",
            "    ERROR_MESSAGE: str = \"[role='alert'].error, .alert-danger, .error-message\"",
            "",
        ]
        return "\n".join(lines)

    def generate_test_class(self, story: Dict[str, Any]) -> str:
        story_id = story.get("id", "generated")
        title = story.get("title", "Generated Test")
        description = story.get("description", "")
        steps = story.get("steps", [])
        tags = story.get("tags", [])
        neg_scenarios = story.get("negative_scenarios", [])
        ts = _timestamp()

        lines: List[str] = []

        # Module docstring
        lines += [
            '"""',
            f"Generated by AI Automation Framework  |  {ts}",
            f"Story : {title}",
            f"ID    : {story_id}",
            '"""',
            "from __future__ import annotations",
            "",
            "import pytest",
            "from playwright.sync_api import Page",
            "",
            "",
            f"class Test{_to_class_name(story_id)}:",
            f'    """{title}',
            "",
            f"    {description}",
            '    """',
            "",
        ]

        # pytest marks + happy-path method
        for tag in tags:
            lines.append(f"    @pytest.mark.{tag}")
        lines.append("    def test_happy_path(self, page: Page, base_url: str) -> None:")
        lines.append(f'        """Happy-path: {title}"""')

        if steps:
            for step in steps:
                code = _action_to_code(
                    step.get("action", ""),
                    step.get("target", ""),
                    step.get("value", ""),
                    step.get("description", ""),
                )
                lines.append(f"        {code}")
        else:
            lines.append("        pass")

        # Negative scenarios
        for scenario in neg_scenarios:
            name = _slug(scenario.get("title", "scenario"))
            expected = scenario.get("expected", "")
            scenario_title = scenario.get("title", "")
            lines += [
                "",
                f"    def test_{name}(self, page: Page, base_url: str) -> None:",
                f'        """{scenario_title}',
                "",
                f"        Expected: {expected}",
                '        """',
                "        # TODO: implement negative scenario steps",
                "        pass",
            ]

        lines.append("")
        return "\n".join(lines)


# ── API Code Generator ────────────────────────────────────────────────────────

class APICodeGenerator:
    """Generates pytest API test classes from API story dicts."""

    def generate_test_class(self, story: Dict[str, Any]) -> str:
        story_id = story.get("id", "generated")
        title = story.get("title", "Generated API Test")
        description = story.get("description", "")
        tags = story.get("tags", [])
        endpoints = story.get("endpoints", [])
        neg_scenarios = story.get("negative_scenarios", [])
        base_url = story.get("base_url", "")
        ts = _timestamp()

        lines: List[str] = []

        lines += [
            '"""',
            f"Generated by AI Automation Framework  |  {ts}",
            f"Story : {title}",
            f"ID    : {story_id}",
            f'Target: {base_url}',
            '"""',
            "from __future__ import annotations",
            "",
            "import pytest",
            "",
            "from services.api_service import APIService",
            "",
            "",
            f"class Test{_to_class_name(story_id)}:",
            f'    """{title}',
            "",
            f"    {description}",
            '    """',
            "",
        ]

        marks = "".join(f"    @pytest.mark.{tag}\n" for tag in tags)

        for endpoint in endpoints:
            ep_id = _slug(endpoint.get("id", "endpoint"))
            method = endpoint.get("method", "GET").lower()
            path = endpoint.get("path", "/")
            body = endpoint.get("body")
            params = endpoint.get("params")
            expected_status = endpoint.get("expected_status", 200)
            expected_schema = endpoint.get("expected_schema", [])
            desc = endpoint.get("description", f"{method.upper()} {path}")

            lines.append(marks.rstrip())
            lines.append(f"    def test_{ep_id}(self, api_client: APIService) -> None:")
            lines.append(f'        """{desc}"""')

            call = _api_call_code(method, path, body, params)
            lines.append(f"        resp = {call}")

            chain = f"        resp.assert_status({expected_status})"
            if expected_schema:
                keys = ", ".join(f'"{k}"' for k in expected_schema)
                chain += f".assert_json_key_exists({keys})"
            lines.append(chain)
            lines.append("")

        for scenario in neg_scenarios:
            name = _slug(scenario.get("id", "negative"))
            scenario_title = scenario.get("title", "")
            expected_status = scenario.get("expected_status", 400)
            method = scenario.get("method", "GET").lower()
            path = scenario.get("path", "/")
            body = scenario.get("body")
            expected = scenario.get("expected", "")

            lines += [
                marks.rstrip(),
                f"    def test_{name}(self, api_client: APIService) -> None:",
                f'        """{scenario_title}',
                "",
                f"        Expected: {expected}",
                '        """',
                f"        resp = {_api_call_code(method, path, body, None)}",
                f"        resp.assert_status({expected_status})",
                "",
            ]

        return "\n".join(lines)


def _api_call_code(
    method: str,
    path: str,
    body: Any,
    params: Any,
) -> str:
    if method == "get":
        if params:
            return f'api_client.get("{path}", params={params!r})'
        return f'api_client.get("{path}")'
    if method == "post":
        return f'api_client.post("{path}", {body!r})'
    if method == "put":
        return f'api_client.put("{path}", {body!r})'
    if method == "patch":
        return f'api_client.patch("{path}", {body!r})'
    if method == "delete":
        return f'api_client.delete("{path}")'
    return f'api_client.get("{path}")  # TODO: unknown method {method!r}'


# ── Module-level helpers ──────────────────────────────────────────────────────

def _infer_action(description: str) -> str:
    low = description.lower()
    if any(k in low for k in ("click", "press", "tap", "submit", "button")):
        return "click"
    if any(k in low for k in ("type", "enter", "fill", "input", "write")):
        return "fill"
    if any(k in low for k in ("navigate", "go to", "open", "visit", "load")):
        return "navigate"
    if any(k in low for k in ("url", "redirect", "route")):
        return "assert_url"
    return "assert_visible"


def _action_to_code(action: str, target: str, value: str, desc: str) -> str:
    comment = f"  # {desc}" if desc else ""
    if action == "navigate":
        return f'page.goto(base_url + "{target}"){comment}'
    if action == "fill":
        return f'page.fill("{target}", "{value}"){comment}'
    if action == "click":
        return f'page.click("{target}"){comment}'
    if action == "assert_url":
        return f'page.wait_for_url("**{target}"){comment}'
    if action == "assert_visible":
        return f'assert page.locator("{target}").is_visible(){comment}'
    if action == "assert_text":
        return f'assert "{value}" in page.locator("{target}").inner_text(){comment}'
    if action == "select":
        return f'page.select_option("{target}", "{value}"){comment}'
    return f'# TODO: implement step — {action} on "{target}"{comment}'


def _camel_to_snake(name: str) -> str:
    s = re.sub(r"(.)([A-Z][a-z]+)", r"\1_\2", name)
    return re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", s).lower()


def _to_class_name(slug: str) -> str:
    return "".join(w.capitalize() for w in re.split(r"[\W_]+", slug) if w)


def _slug(text: str) -> str:
    return re.sub(r"\W+", "_", text.lower()).strip("_")


def _url_path(url: str) -> str:
    from urllib.parse import urlparse
    return urlparse(url).path or "/"


def _timestamp() -> str:
    return datetime.now().isoformat(timespec="seconds")


# ── Project Scaffolder ────────────────────────────────────────────────────────

class ProjectScaffolder:
    """Scaffold a complete test project skeleton for a new target application.

    Generated files are listed in .gitignore — the framework repo stays
    application-agnostic.  Each client adapts the skeleton to their app's DOM/API.

    Usage:
        scaffolder = ProjectScaffolder("https://myapp.com", "myapp", "both")
        scaffolder.scaffold()
    """

    def __init__(self, url: str, name: str, project_type: str = "both") -> None:
        self.url = url.rstrip("/")
        self.name = re.sub(r"[\s\-]+", "_", name.strip().lower())
        self.project_type = project_type
        self.class_name = "".join(w.capitalize() for w in self.name.split("_") if w)

    def scaffold(self) -> list[str]:
        created: list[str] = []
        if self.project_type in ("web", "both"):
            created += self._scaffold_web()
        if self.project_type in ("api", "both"):
            created += self._scaffold_api()
        return created

    # ── Web skeleton ──────────────────────────────────────────────────────────

    def _scaffold_web(self) -> list[str]:
        created = []
        locators_path = Path("locators") / f"{self.name}_locators.py"
        page_path = Path("pages") / f"{self.name}_page.py"
        story_path = Path("stories") / f"{self.name}_story.json"
        test_path = Path("tests") / "workflows" / f"test_{self.name}.py"

        for p in (locators_path, page_path, test_path):
            p.parent.mkdir(parents=True, exist_ok=True)
        story_path.parent.mkdir(parents=True, exist_ok=True)

        if not locators_path.exists():
            locators_path.write_text(self._locators_source(), encoding="utf-8")
            created.append(str(locators_path))

        if not page_path.exists():
            page_path.write_text(self._page_source(), encoding="utf-8")
            created.append(str(page_path))

        if not story_path.exists():
            story_path.write_text(self._web_story_json(), encoding="utf-8")
            created.append(str(story_path))

        if not test_path.exists():
            test_path.write_text(self._web_test_source(), encoding="utf-8")
            created.append(str(test_path))

        return created

    def _locators_source(self) -> str:
        ts = _timestamp()
        cn = self.class_name
        return f'''\
"""
Generated by AI Automation Framework  |  {ts}
Locators for: {cn}

HOW TO UPDATE
  1. Open the target URL in a browser with DevTools (F12)
  2. For each TODO selector below, inspect the real element and replace the placeholder
  3. Prefer [data-test='…'] > #id > .css-class > xpath
  4. Or run: framework inspect --url {self.url}  (requires MCP server)
"""


class {cn}Locators:
    """CSS/attribute selectors for {cn}. All TODOs must be resolved before tests run."""

    # ── Page load indicator (visible only when the page is fully rendered) ─────
    PAGE_INDICATOR: str = "main, [role=\\'main\\'], .main-content"  # TODO: update

    # ── Login form ────────────────────────────────────────────────────────────
    USERNAME_FIELD: str = "[data-test=\\'username\\']"      # TODO: update
    PASSWORD_FIELD: str = "[data-test=\\'password\\']"      # TODO: update
    LOGIN_BUTTON: str = "[data-test=\\'login-button\\']"    # TODO: update
    LOGIN_ERROR: str = "[data-test=\\'error\\']"            # TODO: update

    # ── Post-login dashboard (visible after successful authentication) ─────────
    DASHBOARD_HEADING: str = "h1, .dashboard-title"         # TODO: update
    USER_MENU: str = ".user-menu, [aria-label=\\'user menu\\']"  # TODO: update
    LOGOUT_LINK: str = "[data-test=\\'logout\\'], .logout"  # TODO: update
'''

    def _page_source(self) -> str:
        ts = _timestamp()
        cn = self.class_name
        sn = self.name
        url = self.url
        return f'''\
"""
Generated by AI Automation Framework  |  {ts}
Page Object for: {cn}
Target URL     : {url}
"""
from __future__ import annotations

from playwright.sync_api import Page

from core.base_page import BasePage
from locators.{sn}_locators import {cn}Locators


class {cn}Page(BasePage):
    """Page Object for {cn}. Extend with methods specific to your application."""

    LOGIN_PATH: str = "/"
    DASHBOARD_PATH: str = "/dashboard"  # TODO: update

    def __init__(self, page: Page, base_url: str = "{url}") -> None:
        super().__init__(page, base_url)

    # ── Navigation ────────────────────────────────────────────────────────────

    def navigate_to(self) -> None:
        self.navigate(self.LOGIN_PATH)

    def is_loaded(self) -> bool:
        return self.is_visible({cn}Locators.PAGE_INDICATOR)

    # ── Authentication ────────────────────────────────────────────────────────

    def login(self, username: str, password: str) -> None:
        self.fill({cn}Locators.USERNAME_FIELD, username)
        self.fill({cn}Locators.PASSWORD_FIELD, password)
        self.click({cn}Locators.LOGIN_BUTTON)

    def is_error_visible(self) -> bool:
        return self.is_visible({cn}Locators.LOGIN_ERROR)

    def get_error_message(self) -> str:
        return self.get_text({cn}Locators.LOGIN_ERROR)

    def is_logged_in(self) -> bool:
        return self.is_visible({cn}Locators.DASHBOARD_HEADING)

    def logout(self) -> None:
        self.click({cn}Locators.LOGOUT_LINK)
'''

    def _web_story_json(self) -> str:
        import json
        story = {
            "id": f"{self.name}_login_001",
            "title": f"{self.class_name} User Login",
            "description": f"As a user I want to log in to {self.class_name} so I can access the application.",
            "priority": "critical",
            "tags": ["authentication", "smoke"],
            "base_url": self.url,
            "pages": [f"{self.class_name}Page"],
            "preconditions": [f"Browser is open at {self.url}"],
            "steps": [
                {"id": "step_01", "action": "navigate", "target": "/", "description": "Open login page"},
                {"id": "step_02", "action": "fill", "target": "TODO_USERNAME_SELECTOR", "value": "TODO_USERNAME", "description": "Enter username"},
                {"id": "step_03", "action": "fill", "target": "TODO_PASSWORD_SELECTOR", "value": "TODO_PASSWORD", "description": "Enter password"},
                {"id": "step_04", "action": "click", "target": "TODO_LOGIN_BUTTON_SELECTOR", "description": "Click login"},
                {"id": "step_05", "action": "assert_url", "target": "/dashboard", "description": "Verify redirect — update target path"}
            ],
            "expected_outcomes": [
                "User is redirected to dashboard",
                "No error message is shown"
            ],
            "negative_scenarios": [
                {
                    "id": "neg_01",
                    "title": "Empty credentials show validation error",
                    "steps": ["Leave fields empty", "Click login"],
                    "expected": "Validation error is visible"
                },
                {
                    "id": "neg_02",
                    "title": "Wrong credentials show auth error",
                    "steps": ["Enter wrong credentials", "Click login"],
                    "expected": "Auth error, user stays on login page"
                }
            ]
        }
        return json.dumps(story, indent=2) + "\n"

    def _web_test_source(self) -> str:
        ts = _timestamp()
        cn = self.class_name
        sn = self.name
        url = self.url
        return f'''\
"""
Generated by AI Automation Framework  |  {ts}
Test suite for: {cn}
Target URL    : {url}

HOW TO COMPLETE THIS SKELETON
  1. Update BASE_URL if the login page is not at the root
  2. Replace TODO_USERNAME / TODO_PASSWORD with real credentials
     (load from env vars or a secrets file — never hardcode in source)
  3. Update locators in locators/{sn}_locators.py
  4. Add more test classes (inventory, checkout, …) following this pattern
"""
from __future__ import annotations

import os

import pytest
from playwright.sync_api import Page

from pages.{sn}_page import {cn}Page

BASE_URL = "{url}"
VALID_USER = os.getenv("{cn.upper()}_USERNAME", "TODO_USERNAME")
VALID_PASS = os.getenv("{cn.upper()}_PASSWORD", "TODO_PASSWORD")


@pytest.mark.authentication
@pytest.mark.smoke
class Test{cn}Login:
    """Login flows: happy path + common negative scenarios."""

    def test_login_page_loads(self, page: Page, memory) -> None:
        app = {cn}Page(page, BASE_URL)
        app.navigate_to()
        assert app.is_loaded(), "Login page not visible"

    def test_valid_login_redirects(self, page: Page, memory) -> None:
        app = {cn}Page(page, BASE_URL)
        app.navigate_to()
        app.login(VALID_USER, VALID_PASS)
        assert app.is_logged_in(), "Dashboard not visible after login"
        assert not app.is_error_visible(), "Unexpected error after valid login"

    def test_empty_credentials_show_error(self, page: Page, memory) -> None:
        app = {cn}Page(page, BASE_URL)
        app.navigate_to()
        app.login("", "")
        assert app.is_error_visible(), "Expected validation error for empty credentials"

    def test_wrong_password_shows_error(self, page: Page, memory) -> None:
        app = {cn}Page(page, BASE_URL)
        app.navigate_to()
        app.login(VALID_USER, "definitely_wrong_password")
        assert app.is_error_visible(), "Expected auth error for wrong password"
        assert not app.is_logged_in(), "Should not be logged in with wrong password"
'''

    # ── API skeleton ──────────────────────────────────────────────────────────

    def _scaffold_api(self) -> list[str]:
        created = []
        story_path = Path("stories") / f"{self.name}_api_story.json"
        test_path = Path("tests") / "api" / f"test_{self.name}_api.py"

        story_path.parent.mkdir(parents=True, exist_ok=True)
        test_path.parent.mkdir(parents=True, exist_ok=True)

        if not story_path.exists():
            story_path.write_text(self._api_story_json(), encoding="utf-8")
            created.append(str(story_path))

        if not test_path.exists():
            test_path.write_text(self._api_test_source(), encoding="utf-8")
            created.append(str(test_path))

        return created

    def _api_story_json(self) -> str:
        import json
        story = {
            "id": f"{self.name}_api_001",
            "title": f"{self.class_name} API Availability",
            "description": f"HTTP-level health checks for {self.url}",
            "base_url": self.url,
            "tags": ["api", "smoke"],
            "endpoints": [
                {
                    "id": "root_returns_200",
                    "method": "GET",
                    "path": "/",
                    "description": "Root endpoint returns 200",
                    "expected_status": 200
                }
            ],
            "negative_scenarios": [
                {
                    "id": "neg_01",
                    "title": "Nonexistent path returns 404",
                    "method": "GET",
                    "path": "/nonexistent_path_xyz",
                    "expected_status": 404,
                    "expected": "404 Not Found"
                }
            ]
        }
        return json.dumps(story, indent=2) + "\n"

    def _api_test_source(self) -> str:
        ts = _timestamp()
        cn = self.class_name
        sn = self.name
        url = self.url
        return f'''\
"""
Generated by AI Automation Framework  |  {ts}
API test suite for: {cn}
Target URL      : {url}

HOW TO COMPLETE THIS SKELETON
  1. Update RESPONSE_TIME_MS to reflect your SLA
  2. Add endpoint-specific tests following the pattern below
  3. Use APIResponse fluent assertions — see services/api_response.py for the full API
  4. For authenticated endpoints: client.set_bearer_token(token) before the call
"""
from __future__ import annotations

import pytest

from services.api_service import APIService

BASE_URL = "{url}"
RESPONSE_TIME_MS = 3000


@pytest.fixture(scope="module")
def client() -> APIService:
    return APIService(BASE_URL, max_retries=0)


@pytest.mark.api
@pytest.mark.smoke
class Test{cn}Availability:
    """HTTP-level smoke checks: root reachable, content-type, response time."""

    def test_root_returns_200(self, client: APIService) -> None:
        resp = client.get("/")
        resp.assert_ok()

    def test_root_response_time_under_budget(self, client: APIService) -> None:
        resp = client.get("/")
        resp.assert_ok().assert_response_time(RESPONSE_TIME_MS)

    def test_root_body_not_empty(self, client: APIService) -> None:
        resp = client.get("/")
        resp.assert_ok().assert_not_empty()


@pytest.mark.api
@pytest.mark.regression
class Test{cn}Endpoints:
    """Extend this class with endpoint-specific tests for {cn}."""

    def test_nonexistent_path_returns_404(self, client: APIService) -> None:
        resp = client.get("/nonexistent_path_xyz_99999")
        resp.assert_not_found()

    # TODO: add endpoint tests below — examples:
    #
    # def test_list_users(self, client: APIService) -> None:
    #     resp = client.get("/users")
    #     resp.assert_ok()\\
    #        .assert_json_list_not_empty("data")\\
    #        .assert_json_list_items_have_keys("data", "id", "email")
    #
    # def test_create_user(self, client: APIService) -> None:
    #     resp = client.post("/users", {{"name": "Test", "email": "test@example.com"}})
    #     resp.assert_created()\\
    #        .assert_json_key_exists("id")\\
    #        .assert_response_time(RESPONSE_TIME_MS)
'''
