"""
Utility helpers: story file parsing and Python source code generation.
"""
from __future__ import annotations

import json
import re
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List
import logging

logger = logging.getLogger(__name__)


# ── Story Parser ──────────────────────────────────────────────────────────────

class StoryParser:
    """Reads user story files (.json or .txt/.md) into a normalized dict."""

    REQUIRED_FIELDS = {"id", "title", "steps"}

    def parse_story_file(self, path: str) -> Dict[str, Any]:
        file_path = Path(path)
        if not file_path.exists():
            raise FileNotFoundError(f"Story file not found: {path}")

        suffix = file_path.suffix.lower()
        if suffix == ".json":
            return self._parse_json(file_path)
        if suffix in (".txt", ".md"):
            return self._parse_text(file_path)
        raise ValueError(f"Unsupported story file format: {suffix!r}")

    def _parse_json(self, path: Path) -> Dict[str, Any]:
        with open(path, encoding="utf-8") as f:
            data = json.load(f)
        self._validate(data, path)
        return data

    def _parse_text(self, path: Path) -> Dict[str, Any]:
        lines = [ln.strip() for ln in path.read_text(encoding="utf-8").splitlines() if ln.strip()]
        story: Dict[str, Any] = {
            "id": path.stem,
            "title": lines[0] if lines else "Untitled Story",
            "description": "",
            "steps": [],
            "tags": [],
        }
        counter = 1
        for line in lines[1:]:
            low = line.lower()
            if low.startswith(("given ", "when ", "then ", "and ")):
                _, _, desc = line.partition(" ")
                story["steps"].append({
                    "id": f"step_{counter:02d}",
                    "action": _infer_action(desc),
                    "target": "",
                    "value": "",
                    "description": line,
                })
                counter += 1
            elif not story["description"]:
                story["description"] = line
        return story

    def _validate(self, data: Dict, path: Path) -> None:
        missing = self.REQUIRED_FIELDS - set(data)
        if missing:
            raise ValueError(f"{path.name}: missing required fields {missing}")


# ── Code Generator ────────────────────────────────────────────────────────────

class CodeGenerator:
    """Generates production-ready Page Object and pytest test source from story data."""

    def generate_page_class(self, page_name: str, url: str) -> str:
        snake = _camel_to_snake(page_name)
        path = _url_path(url)
        ts = _timestamp()

        lines = [
            f'"""',
            f"Generated by AI Automation Framework  |  {ts}",
            f"Page  : {page_name}",
            f"URL   : {url}",
            f'"""',
            "from __future__ import annotations",
            "",
            "from playwright.sync_api import Page",
            "",
            "from core.base_page import BasePage",
            f"from locators.{snake}_locators import {page_name}Locators",
            "",
            "",
            f"class {page_name}(BasePage):",
            f'    """Page Object for {page_name}."""',
            "",
            f'    URL_PATH: str = "{path}"',
            "",
            "    def __init__(self, page: Page, base_url: str = \"\") -> None:",
            "        super().__init__(page, base_url)",
            "",
            "    # ── Navigation ────────────────────────────────────────────────────",
            "",
            "    def navigate_to(self) -> None:",
            "        self.navigate(self.URL_PATH)",
            "",
            "    # ── Actions ───────────────────────────────────────────────────────",
            "",
            "    def click_primary_action(self) -> None:",
            f"        self.click({page_name}Locators.PRIMARY_ACTION)",
            "",
            "    def fill_primary_input(self, value: str) -> None:",
            f"        self.fill({page_name}Locators.PRIMARY_INPUT, value)",
            "",
            "    # ── Assertions ────────────────────────────────────────────────────",
            "",
            "    def is_loaded(self) -> bool:",
            f"        return self.is_visible({page_name}Locators.PAGE_INDICATOR)",
            "",
            "    def get_heading(self) -> str:",
            f"        return self.get_text({page_name}Locators.PAGE_HEADING)",
            "",
        ]
        return "\n".join(lines)

    def generate_locator_class(self, page_name: str) -> str:
        ts = _timestamp()

        lines = [
            f'"""',
            f"Generated by AI Automation Framework  |  {ts}",
            f"Locators for: {page_name}",
            "Update selectors after running inspect_current_dom via the MCP server.",
            f'"""',
            "",
            "",
            f"class {page_name}Locators:",
            f'    """CSS/XPath selectors for {page_name}. Update after DOM inspection."""',
            "",
            "    # Page structural indicators",
            "    PAGE_INDICATOR: str = \"main, [role='main'], #main-content\"",
            "    PAGE_HEADING: str = \"h1\"",
            "",
            "    # Primary interactive elements (update after DOM inspection)",
            "    PRIMARY_ACTION: str = \"button[type='submit'], .btn-primary\"",
            "    PRIMARY_INPUT: str = \"input:not([type='hidden'])\"",
            "",
            "    # Status / feedback",
            "    SUCCESS_MESSAGE: str = \"[role='alert'].success, .alert-success\"",
            "    ERROR_MESSAGE: str = \"[role='alert'].error, .alert-danger, .error-message\"",
            "",
        ]
        return "\n".join(lines)

    def generate_test_class(self, story: Dict[str, Any]) -> str:
        story_id = story.get("id", "generated")
        title = story.get("title", "Generated Test")
        description = story.get("description", "")
        steps = story.get("steps", [])
        tags = story.get("tags", [])
        neg_scenarios = story.get("negative_scenarios", [])
        ts = _timestamp()

        lines: List[str] = []

        # Module docstring
        lines += [
            '"""',
            f"Generated by AI Automation Framework  |  {ts}",
            f"Story : {title}",
            f"ID    : {story_id}",
            '"""',
            "from __future__ import annotations",
            "",
            "import pytest",
            "from playwright.sync_api import Page",
            "",
            "",
            f"class Test{_to_class_name(story_id)}:",
            f'    """{title}',
            "",
            f"    {description}",
            '    """',
            "",
        ]

        # pytest marks + happy-path method
        for tag in tags:
            lines.append(f"    @pytest.mark.{tag}")
        lines.append("    def test_happy_path(self, page: Page, base_url: str) -> None:")
        lines.append(f'        """Happy-path: {title}"""')

        if steps:
            for step in steps:
                code = _action_to_code(
                    step.get("action", ""),
                    step.get("target", ""),
                    step.get("value", ""),
                    step.get("description", ""),
                )
                lines.append(f"        {code}")
        else:
            lines.append("        pass")

        # Negative scenarios
        for scenario in neg_scenarios:
            name = _slug(scenario.get("title", "scenario"))
            expected = scenario.get("expected", "")
            scenario_title = scenario.get("title", "")
            lines += [
                "",
                f"    def test_{name}(self, page: Page, base_url: str) -> None:",
                f'        """{scenario_title}',
                "",
                f"        Expected: {expected}",
                '        """',
                "        # TODO: implement negative scenario steps",
                "        pass",
            ]

        lines.append("")
        return "\n".join(lines)


# ── API Code Generator ────────────────────────────────────────────────────────

class APICodeGenerator:
    """Generates pytest API test classes from API story dicts."""

    def generate_test_class(self, story: Dict[str, Any]) -> str:
        story_id = story.get("id", "generated")
        title = story.get("title", "Generated API Test")
        description = story.get("description", "")
        tags = story.get("tags", [])
        endpoints = story.get("endpoints", [])
        neg_scenarios = story.get("negative_scenarios", [])
        base_url = story.get("base_url", "")
        ts = _timestamp()

        lines: List[str] = []

        lines += [
            '"""',
            f"Generated by AI Automation Framework  |  {ts}",
            f"Story : {title}",
            f"ID    : {story_id}",
            f'Target: {base_url}',
            '"""',
            "from __future__ import annotations",
            "",
            "import pytest",
            "",
            "from services.api_service import APIService",
            "",
            "",
            f"class Test{_to_class_name(story_id)}:",
            f'    """{title}',
            "",
            f"    {description}",
            '    """',
            "",
        ]

        marks = "".join(f"    @pytest.mark.{tag}\n" for tag in tags)

        for endpoint in endpoints:
            ep_id = _slug(endpoint.get("id", "endpoint"))
            method = endpoint.get("method", "GET").lower()
            path = endpoint.get("path", "/")
            body = endpoint.get("body")
            params = endpoint.get("params")
            expected_status = endpoint.get("expected_status", 200)
            expected_schema = endpoint.get("expected_schema", [])
            desc = endpoint.get("description", f"{method.upper()} {path}")

            lines.append(marks.rstrip())
            lines.append(f"    def test_{ep_id}(self, api_client: APIService) -> None:")
            lines.append(f'        """{desc}"""')

            call = _api_call_code(method, path, body, params)
            lines.append(f"        resp = {call}")

            chain = f"        resp.assert_status({expected_status})"
            if expected_schema:
                keys = ", ".join(f'"{k}"' for k in expected_schema)
                chain += f".assert_json_key_exists({keys})"
            lines.append(chain)
            lines.append("")

        for scenario in neg_scenarios:
            name = _slug(scenario.get("id", "negative"))
            scenario_title = scenario.get("title", "")
            expected_status = scenario.get("expected_status", 400)
            method = scenario.get("method", "GET").lower()
            path = scenario.get("path", "/")
            body = scenario.get("body")
            expected = scenario.get("expected", "")

            lines += [
                marks.rstrip(),
                f"    def test_{name}(self, api_client: APIService) -> None:",
                f'        """{scenario_title}',
                "",
                f"        Expected: {expected}",
                '        """',
                f"        resp = {_api_call_code(method, path, body, None)}",
                f"        resp.assert_status({expected_status})",
                "",
            ]

        return "\n".join(lines)


def _api_call_code(
    method: str,
    path: str,
    body: Any,
    params: Any,
) -> str:
    if method == "get":
        if params:
            return f'api_client.get("{path}", params={params!r})'
        return f'api_client.get("{path}")'
    if method == "post":
        return f'api_client.post("{path}", {body!r})'
    if method == "put":
        return f'api_client.put("{path}", {body!r})'
    if method == "patch":
        return f'api_client.patch("{path}", {body!r})'
    if method == "delete":
        return f'api_client.delete("{path}")'
    return f'api_client.get("{path}")  # TODO: unknown method {method!r}'


# ── Module-level helpers ──────────────────────────────────────────────────────

def _infer_action(description: str) -> str:
    low = description.lower()
    if any(k in low for k in ("click", "press", "tap", "submit", "button")):
        return "click"
    if any(k in low for k in ("type", "enter", "fill", "input", "write")):
        return "fill"
    if any(k in low for k in ("navigate", "go to", "open", "visit", "load")):
        return "navigate"
    if any(k in low for k in ("url", "redirect", "route")):
        return "assert_url"
    return "assert_visible"


def _action_to_code(action: str, target: str, value: str, desc: str) -> str:
    comment = f"  # {desc}" if desc else ""
    if action == "navigate":
        return f'page.goto(base_url + "{target}"){comment}'
    if action == "fill":
        return f'page.fill("{target}", "{value}"){comment}'
    if action == "click":
        return f'page.click("{target}"){comment}'
    if action == "assert_url":
        return f'page.wait_for_url("**{target}"){comment}'
    if action == "assert_visible":
        return f'assert page.locator("{target}").is_visible(){comment}'
    if action == "assert_text":
        return f'assert "{value}" in page.locator("{target}").inner_text(){comment}'
    if action == "select":
        return f'page.select_option("{target}", "{value}"){comment}'
    return f'# TODO: implement step — {action} on "{target}"{comment}'


def _camel_to_snake(name: str) -> str:
    s = re.sub(r"(.)([A-Z][a-z]+)", r"\1_\2", name)
    return re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", s).lower()


def _to_class_name(slug: str) -> str:
    return "".join(w.capitalize() for w in re.split(r"[\W_]+", slug) if w)


def _slug(text: str) -> str:
    return re.sub(r"\W+", "_", text.lower()).strip("_")


def _url_path(url: str) -> str:
    from urllib.parse import urlparse
    return urlparse(url).path or "/"


def _timestamp() -> str:
    return datetime.now().isoformat(timespec="seconds")
