"""
Utility helpers: story file parsing and Python source code generation.
"""
from __future__ import annotations

import json
import re
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List
from urllib.parse import urlparse
import logging

logger = logging.getLogger(__name__)


# ── URL Safety Helper ─────────────────────────────────────────────────────────

def is_safe_probe_url(url: str) -> tuple[bool, str]:
    """Return (True, "") if url is safe to hand to a browser/probe, else (False, reason).

    Allows only http/https. Rejects file:, javascript:, data:, ftp:, gopher:, about:,
    blank, non-string, and over-long (>2048) inputs.

    NOTE: localhost and RFC-1918 private IP addresses are intentionally allowed —
    testing apps on localhost or internal networks is a primary use case of this
    framework. Do NOT add blocks for 127.x, 192.168.x, 10.x, etc.
    """
    if not isinstance(url, str):
        return False, "URL must be a string"
    if not url or not url.strip():
        return False, "URL must not be empty"
    if len(url) > 2048:
        return False, "URL exceeds maximum allowed length of 2048 characters"
    try:
        parsed = urlparse(url)
    except Exception as exc:
        return False, f"URL could not be parsed: {exc}"
    if parsed.scheme not in {"http", "https"}:
        return False, f"Scheme {parsed.scheme!r} is not allowed; only http and https are permitted"
    if not parsed.netloc:
        return False, "URL has no host/netloc component"
    return True, ""


# ── Story Parser ──────────────────────────────────────────────────────────────

class StoryParser:
    """Reads user story files (.json or .txt/.md) into a normalized dict."""

    REQUIRED_FIELDS = {"id", "title", "steps"}

    def parse_story_file(self, path: str) -> Dict[str, Any]:
        file_path = Path(path)
        if not file_path.exists():
            raise FileNotFoundError(f"Story file not found: {path}")

        suffix = file_path.suffix.lower()
        if suffix == ".json":
            return self._parse_json(file_path)
        if suffix in (".txt", ".md"):
            return self._parse_text(file_path)
        raise ValueError(f"Unsupported story file format: {suffix!r}")

    def _parse_json(self, path: Path) -> Dict[str, Any]:
        with open(path, encoding="utf-8") as f:
            data = json.load(f)
        self._validate(data, path)
        return data

    def _parse_text(self, path: Path) -> Dict[str, Any]:
        lines = [ln.strip() for ln in path.read_text(encoding="utf-8").splitlines() if ln.strip()]
        story: Dict[str, Any] = {
            "id": path.stem,
            "title": lines[0] if lines else "Untitled Story",
            "description": "",
            "steps": [],
            "tags": [],
        }
        counter = 1
        for line in lines[1:]:
            low = line.lower()
            if low.startswith(("given ", "when ", "then ", "and ")):
                _, _, desc = line.partition(" ")
                story["steps"].append({
                    "id": f"step_{counter:02d}",
                    "action": _infer_action(desc),
                    "target": "",
                    "value": "",
                    "description": line,
                })
                counter += 1
            elif not story["description"]:
                story["description"] = line
        return story

    def _validate(self, data: Dict, path: Path) -> None:
        missing = self.REQUIRED_FIELDS - set(data)
        if missing:
            raise ValueError(f"{path.name}: missing required fields {missing}")


# ── Code Generator ────────────────────────────────────────────────────────────

class CodeGenerator:
    """Generates production-ready Page Object and pytest test source from story data."""

    def generate_page_class(self, page_name: str, url: str) -> str:
        snake = _camel_to_snake(page_name)
        path = _url_path(url)
        ts = _timestamp()

        lines = [
            f'"""',
            f"Generated by AI Automation Framework  |  {ts}",
            f"Page  : {page_name}",
            f"URL   : {url}",
            f'"""',
            "from __future__ import annotations",
            "",
            "from playwright.sync_api import Page",
            "",
            "from core.base_page import BasePage",
            f"from locators.{snake}_locators import {page_name}Locators",
            "",
            "",
            f"class {page_name}(BasePage):",
            f'    """Page Object for {page_name}."""',
            "",
            f'    URL_PATH: str = "{path}"',
            "",
            "    def __init__(self, page: Page, base_url: str = \"\") -> None:",
            "        super().__init__(page, base_url)",
            "",
            "    # ── Navigation ────────────────────────────────────────────────────",
            "",
            "    def navigate_to(self) -> None:",
            "        self.navigate(self.URL_PATH)",
            "",
            "    # ── Actions ───────────────────────────────────────────────────────",
            "",
            "    def click_primary_action(self) -> None:",
            f"        self.click({page_name}Locators.PRIMARY_ACTION)",
            "",
            "    def fill_primary_input(self, value: str) -> None:",
            f"        self.fill({page_name}Locators.PRIMARY_INPUT, value)",
            "",
            "    # ── Assertions ────────────────────────────────────────────────────",
            "",
            "    def is_loaded(self) -> bool:",
            f"        return self.is_visible({page_name}Locators.PAGE_INDICATOR)",
            "",
            "    def get_heading(self) -> str:",
            f"        return self.get_text({page_name}Locators.PAGE_HEADING)",
            "",
        ]
        return "\n".join(lines)

    def generate_locator_class(self, page_name: str) -> str:
        ts = _timestamp()

        lines = [
            f'"""',
            f"Generated by AI Automation Framework  |  {ts}",
            f"Locators for: {page_name}",
            "Update selectors after running inspect_current_dom via the MCP server.",
            f'"""',
            "",
            "",
            f"class {page_name}Locators:",
            f'    """CSS/XPath selectors for {page_name}. Update after DOM inspection."""',
            "",
            "    # Page structural indicators",
            "    PAGE_INDICATOR: str = \"main, [role='main'], #main-content\"",
            "    PAGE_HEADING: str = \"h1\"",
            "",
            "    # Primary interactive elements (update after DOM inspection)",
            "    PRIMARY_ACTION: str = \"button[type='submit'], .btn-primary\"",
            "    PRIMARY_INPUT: str = \"input:not([type='hidden'])\"",
            "",
            "    # Status / feedback",
            "    SUCCESS_MESSAGE: str = \"[role='alert'].success, .alert-success\"",
            "    ERROR_MESSAGE: str = \"[role='alert'].error, .alert-danger, .error-message\"",
            "",
        ]
        return "\n".join(lines)

    def generate_test_class(self, story: Dict[str, Any]) -> str:
        story_id = story.get("id", "generated")
        title = story.get("title", "Generated Test")
        description = story.get("description", "")
        steps = story.get("steps", [])
        tags = story.get("tags", [])
        neg_scenarios = story.get("negative_scenarios", [])
        ts = _timestamp()

        lines: List[str] = []

        # Module docstring
        lines += [
            '"""',
            f"Generated by AI Automation Framework  |  {ts}",
            f"Story : {title}",
            f"ID    : {story_id}",
            '"""',
            "from __future__ import annotations",
            "",
            "import pytest",
            "from playwright.sync_api import Page",
            "",
            "",
            f"class Test{_to_class_name(story_id)}:",
            f'    """{title}',
            "",
            f"    {description}",
            '    """',
            "",
        ]

        # pytest marks + happy-path method
        for tag in tags:
            lines.append(f"    @pytest.mark.{tag}")
        lines.append("    def test_happy_path(self, page: Page, base_url: str) -> None:")
        lines.append(f'        """Happy-path: {title}"""')

        if steps:
            for step in steps:
                code = _action_to_code(
                    step.get("action", ""),
                    step.get("target", ""),
                    step.get("value", ""),
                    step.get("description", ""),
                )
                lines.append(f"        {code}")
        else:
            lines.append("        pass")

        # Negative scenarios
        for scenario in neg_scenarios:
            name = _slug(scenario.get("title", "scenario"))
            expected = scenario.get("expected", "")
            scenario_title = scenario.get("title", "")
            lines += [
                "",
                f"    def test_{name}(self, page: Page, base_url: str) -> None:",
                f'        """{scenario_title}',
                "",
                f"        Expected: {expected}",
                '        """',
                "        # TODO: implement negative scenario steps",
                "        pass",
            ]

        lines.append("")
        return "\n".join(lines)


# ── API Code Generator ────────────────────────────────────────────────────────

class APICodeGenerator:
    """Generates pytest API test classes from API story dicts."""

    def generate_test_class(self, story: Dict[str, Any]) -> str:
        story_id = story.get("id", "generated")
        title = story.get("title", "Generated API Test")
        description = story.get("description", "")
        tags = story.get("tags", [])
        endpoints = story.get("endpoints", [])
        neg_scenarios = story.get("negative_scenarios", [])
        base_url = story.get("base_url", "")
        ts = _timestamp()

        lines: List[str] = []

        lines += [
            '"""',
            f"Generated by AI Automation Framework  |  {ts}",
            f"Story : {title}",
            f"ID    : {story_id}",
            f'Target: {base_url}',
            '"""',
            "from __future__ import annotations",
            "",
            "import pytest",
            "",
            "from services.api_service import APIService",
            "",
            "",
            f"class Test{_to_class_name(story_id)}:",
            f'    """{title}',
            "",
            f"    {description}",
            '    """',
            "",
        ]

        marks = "".join(f"    @pytest.mark.{tag}\n" for tag in tags)

        for endpoint in endpoints:
            ep_id = _slug(endpoint.get("id", "endpoint"))
            method = endpoint.get("method", "GET").lower()
            path = endpoint.get("path", "/")
            body = endpoint.get("body")
            params = endpoint.get("params")
            expected_status = endpoint.get("expected_status", 200)
            expected_schema = endpoint.get("expected_schema", [])
            desc = endpoint.get("description", f"{method.upper()} {path}")

            lines.append(marks.rstrip())
            lines.append(f"    def test_{ep_id}(self, api_client: APIService) -> None:")
            lines.append(f'        """{desc}"""')

            call = _api_call_code(method, path, body, params)
            lines.append(f"        resp = {call}")

            chain = f"        resp.assert_status({expected_status})"
            if expected_schema:
                keys = ", ".join(f'"{k}"' for k in expected_schema)
                chain += f".assert_json_key_exists({keys})"
            lines.append(chain)
            lines.append("")

        for scenario in neg_scenarios:
            name = _slug(scenario.get("id", "negative"))
            scenario_title = scenario.get("title", "")
            expected_status = scenario.get("expected_status", 400)
            method = scenario.get("method", "GET").lower()
            path = scenario.get("path", "/")
            body = scenario.get("body")
            expected = scenario.get("expected", "")

            lines += [
                marks.rstrip(),
                f"    def test_{name}(self, api_client: APIService) -> None:",
                f'        """{scenario_title}',
                "",
                f"        Expected: {expected}",
                '        """',
                f"        resp = {_api_call_code(method, path, body, None)}",
                f"        resp.assert_status({expected_status})",
                "",
            ]

        return "\n".join(lines)


def _api_call_code(
    method: str,
    path: str,
    body: Any,
    params: Any,
) -> str:
    if method == "get":
        if params:
            return f'api_client.get("{path}", params={params!r})'
        return f'api_client.get("{path}")'
    if method == "post":
        return f'api_client.post("{path}", {body!r})'
    if method == "put":
        return f'api_client.put("{path}", {body!r})'
    if method == "patch":
        return f'api_client.patch("{path}", {body!r})'
    if method == "delete":
        return f'api_client.delete("{path}")'
    return f'api_client.get("{path}")  # TODO: unknown method {method!r}'


# ── Module-level helpers ──────────────────────────────────────────────────────

def _infer_action(description: str) -> str:
    low = description.lower()
    if any(k in low for k in ("click", "press", "tap", "submit", "button")):
        return "click"
    if any(k in low for k in ("type", "enter", "fill", "input", "write")):
        return "fill"
    if any(k in low for k in ("navigate", "go to", "open", "visit", "load")):
        return "navigate"
    if any(k in low for k in ("url", "redirect", "route")):
        return "assert_url"
    return "assert_visible"


def _action_to_code(action: str, target: str, value: str, desc: str) -> str:
    comment = f"  # {desc}" if desc else ""
    if action == "navigate":
        return f'page.goto(base_url + "{target}"){comment}'
    if action == "fill":
        return f'page.fill("{target}", "{value}"){comment}'
    if action == "click":
        return f'page.click("{target}"){comment}'
    if action == "assert_url":
        return f'page.wait_for_url("**{target}"){comment}'
    if action == "assert_visible":
        return f'assert page.locator("{target}").is_visible(){comment}'
    if action == "assert_text":
        return f'assert "{value}" in page.locator("{target}").inner_text(){comment}'
    if action == "select":
        return f'page.select_option("{target}", "{value}"){comment}'
    return f'pytest.fail("Unsupported action {action!r} — story step not implemented (target: {target!r})"){comment}'


def _camel_to_snake(name: str) -> str:
    s = re.sub(r"(.)([A-Z][a-z]+)", r"\1_\2", name)
    return re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", s).lower()


def _to_class_name(slug: str) -> str:
    return "".join(w.capitalize() for w in re.split(r"[\W_]+", slug) if w)


def _slug(text: str) -> str:
    return re.sub(r"\W+", "_", text.lower()).strip("_")


def _url_path(url: str) -> str:
    from urllib.parse import urlparse
    return urlparse(url).path or "/"


def _timestamp() -> str:
    return datetime.now().isoformat(timespec="seconds")


# ── Natural Language Story Parser ─────────────────────────────────────────────

class NaturalLanguageStoryParser:
    """Convert plain-English test requirements to structured story JSON.

    Handles free-form English, bullet lists, numbered lists, and Gherkin-style
    Given/When/Then. Output is story JSON consumable by AutoDOMMapper and CodeGenerator.
    """

    _ACTION_PATTERNS: List[tuple] = [
        (["navigate to", "go to", "open", "visit", "load", "access", "browse to"], "navigate"),
        (["enter", "fill in", "fill", "type", "input", "set", "write", "provide"], "fill"),
        (["click", "press", "tap", "select", "choose", "hit", "submit", "push", "tap on"], "click"),
        (["log in", "login", "sign in", "signin", "authenticate", "log into"], "login"),
        (["log out", "logout", "sign out", "signout"], "logout"),
        (["see", "verify", "check", "confirm", "assert", "expect", "should see",
          "ensure", "validate", "observe", "notice"], "assert_visible"),
        (["redirect", "land on", "be on", "url should", "should be taken to",
          "taken to", "be directed to"], "assert_url"),
    ]

    _STOP_WORDS = {
        "as", "a", "an", "the", "i", "user", "admin", "manager", "want", "to", "be",
        "able", "and", "or", "with", "my", "their", "our", "this", "that", "it",
        "is", "are", "was", "were", "will", "would", "should", "can", "could",
        "have", "has", "had", "do", "does", "did",
    }

    _NEGATIVE_MARKERS = [
        "negative", "error case", "invalid", "fail", "reject", "deny",
        "incorrect", "wrong", "bad", "missing", "empty", "not found",
    ]

    def parse(self, text: str) -> List[Dict[str, Any]]:
        """Parse a block of English text into one or more story dicts."""
        blocks = self._split_stories(text)
        return [self._parse_one(block.strip(), idx) for idx, block in enumerate(blocks, 1)
                if block.strip()]

    def _split_stories(self, text: str) -> List[str]:
        return re.split(
            r'\n\s*---+\s*\n|\n\s*[Ss]tory\s+\d+\s*:\s*\n|\n\s*[Ss]cenario\s+\d+\s*:\s*\n',
            text
        )

    def _parse_one(self, text: str, index: int) -> Dict[str, Any]:
        lines = [l.strip() for l in text.splitlines() if l.strip()]
        if not lines:
            return {}

        title, description, actor = self._extract_header(lines[0])
        story_id = self._make_id(title, index)
        steps: List[Dict] = []
        step_num = 1

        content_lines = lines[1:] if len(lines) > 1 else lines
        for line in content_lines:
            parsed = self._parse_line(line)
            if not parsed:
                continue
            expanded = self._expand_compound(parsed, step_num)
            for s in expanded:
                steps.append(s)
                step_num += 1

        if not steps:
            steps = [{"id": "step_01", "action": "navigate", "target": "TODO__NAVIGATE",
                       "value": "", "description": "Navigate to application"}]

        return {
            "id": story_id,
            "title": title,
            "description": description,
            "actor": actor,
            "tags": self._infer_tags(title + " " + text),
            "base_url": "",
            "steps": steps,
            "negative_scenarios": self._extract_negatives(text),
        }

    def _extract_header(self, line: str) -> tuple:
        m = re.match(
            r'[Aa]s (?:a[n]? )?(.+?)[,.]?\s+[Ii]\s+want(?:\s+to)?\s+(.+?)(?:\s+so that.+)?$',
            line
        )
        if m:
            actor = m.group(1).strip()
            intent = m.group(2).strip()[:80]
            return f"{actor.title()} — {intent}", line.strip(), actor

        m = re.match(r'[Tt]est(?:ing)?\s+that\s+(.+)', line)
        if m:
            return m.group(1).strip()[:80], line.strip(), "user"

        return line.strip()[:80], line.strip(), "user"

    def _make_id(self, title: str, index: int) -> str:
        clean = re.sub(r"[^a-z0-9\s]", "", title.lower())
        words = [w for w in clean.split() if w not in self._STOP_WORDS][:4]
        slug = "_".join(words) if words else "story"
        return f"{slug}_{index:03d}"

    def _parse_line(self, line: str) -> Dict | None:
        line = re.sub(r"^[\d]+[.)]\s*|^[-*•»]\s*|^(Given|When|Then|And)\s+", "", line).strip()
        if not line or line.endswith(":") or line.startswith("#"):
            return None

        action, value = self._classify(line)
        return {
            "id": "step_XX",
            "action": action,
            "target": f"TODO__{action.upper()}",
            "value": value,
            "description": line,
        }

    def _classify(self, line: str) -> tuple:
        low = line.lower()
        for patterns, action in self._ACTION_PATTERNS:
            if any(p in low for p in patterns):
                return action, self._extract_value(line)
        return "assert_visible", ""

    def _extract_value(self, line: str) -> str:
        m = re.search(r'["\']([^"\']+)["\']', line)
        if m:
            return m.group(1)
        m = re.search(r'\b(?:with|using|value|text)\s+["\']?([A-Za-z0-9@._-]+)["\']?', line.lower())
        if m:
            return m.group(1)
        return ""

    def _expand_compound(self, step: Dict, num: int) -> List[Dict]:
        action = step.get("action")
        base = {k: v for k, v in step.items() if k != "id"}

        if action == "login":
            return [
                {**base, "id": f"step_{num:02d}", "action": "fill",
                 "target": "TODO__USERNAME_FIELD", "value": "TODO_USERNAME",
                 "description": "Enter username"},
                {**base, "id": f"step_{num+1:02d}", "action": "fill",
                 "target": "TODO__PASSWORD_FIELD", "value": "TODO_PASSWORD",
                 "description": "Enter password"},
                {**base, "id": f"step_{num+2:02d}", "action": "click",
                 "target": "TODO__LOGIN_BUTTON", "description": "Click login button"},
                {**base, "id": f"step_{num+3:02d}", "action": "assert_url",
                 "target": "TODO__POST_LOGIN_PATH",
                 "description": "Verify redirect after login — update target path for your app"},
            ]

        if action == "logout":
            return [
                {**base, "id": f"step_{num:02d}", "action": "click",
                 "target": "TODO__LOGOUT_LINK", "description": "Click logout"},
                {**base, "id": f"step_{num+1:02d}", "action": "assert_url",
                 "target": "TODO__LOGIN_PATH",
                 "description": "Verify redirect to login page — update target path for your app"},
            ]

        return [{**step, "id": f"step_{num:02d}"}]

    def _infer_tags(self, text: str) -> List[str]:
        text = text.lower()
        tags: List[str] = ["smoke"]
        if any(w in text for w in ("login", "logout", "auth", "sign in", "password", "credential")):
            tags.append("authentication")
        if any(w in text for w in ("checkout", "purchase", "payment", "order", "buy", "cart")):
            tags.append("checkout")
        if any(w in text for w in ("api", "endpoint", "rest", "http", "request", "response", "json")):
            tags.append("api")
        return tags

    def _extract_negatives(self, text: str) -> List[Dict]:
        negatives: List[Dict] = []
        for marker in self._NEGATIVE_MARKERS:
            for m in re.finditer(rf'{marker}[:\s]+([^\n.]+)', text.lower()):
                desc = m.group(1).strip()[:80]
                if len(desc) > 5:
                    negatives.append({
                        "id": f"neg_{len(negatives)+1:02d}",
                        "title": f"Invalid — {desc}",
                        "expected": "Error message displayed or action rejected",
                    })
        return negatives[:5]  # cap at 5 negative scenarios


# ── DOM Prober (synchronous — for CLI use) ────────────────────────────────────

class DOMProber:
    """Synchronous Playwright DOM prober used by AutoDOMMapper in the CLI pipeline.

    Uses sync_playwright so it runs in a normal function context (no asyncio needed).
    The MCP server uses async_playwright; this is the CLI equivalent.
    """

    _JS_EXTRACT = """() => {
        const sel = [
            'button', 'a[href]', 'input:not([type="hidden"])', 'select',
            'textarea', '[data-test]', '[data-testid]', '[aria-label]',
            '[role="button"]', '[role="link"]', '[role="checkbox"]'
        ].join(', ');
        return Array.from(document.querySelectorAll(sel))
            .filter(el => {
                const r = el.getBoundingClientRect();
                return r.width > 0 && r.height > 0;
            })
            .slice(0, 80)
            .map(el => ({
                tag:          el.tagName.toLowerCase(),
                id:           el.id || null,
                dataTest:     el.getAttribute('data-test') || el.getAttribute('data-testid') || null,
                dataTestAttr: el.hasAttribute('data-test') ? 'data-test'
                              : el.hasAttribute('data-testid') ? 'data-testid' : null,
                ariaLabel:    el.getAttribute('aria-label') || null,
                placeholder:  el.getAttribute('placeholder') || null,
                text:         (el.innerText || el.textContent || '').trim().slice(0, 80),
                type:         el.getAttribute('type') || null,
                name:         el.getAttribute('name') || null,
                href:         el.getAttribute('href') || null,
                autocomplete: el.getAttribute('autocomplete') || null,
                className:    (el.className || '').toString().slice(0, 100),
            }));
    }"""

    def probe(self, url: str, credentials: Dict | None = None) -> Dict[str, Any]:
        """Navigate to url, optionally auto-login, return element list.

        Load strategy: tries networkidle first (best for server-rendered apps).
        Falls back to domcontentloaded + 2 s extra wait for SPAs (React, Angular,
        Vue) that keep the network alive via WebSockets or polling.
        """
        try:
            from playwright.sync_api import sync_playwright, TimeoutError as PWTimeout
        except ImportError:
            return {"status": "error", "error": "playwright not installed — run: pip install playwright && playwright install"}

        with sync_playwright() as p:
            browser = p.chromium.launch(headless=True)
            page = browser.new_page()
            try:
                # Primary strategy: networkidle
                try:
                    page.goto(url, wait_until="networkidle", timeout=20_000)
                except PWTimeout:
                    # SPA fallback: domcontentloaded + settle time
                    logger.debug("networkidle timed out for %s — falling back to domcontentloaded", url)
                    page.goto(url, wait_until="domcontentloaded", timeout=20_000)
                    page.wait_for_timeout(2_500)

                # Auto-login if we landed on a login page (URL hint OR password field present)
                if credentials and self._looks_like_login_page(page.url, page):
                    self._try_login(page, credentials)
                    # Wait for post-login navigation to settle
                    try:
                        page.wait_for_load_state("networkidle", timeout=10_000)
                    except PWTimeout:
                        page.wait_for_timeout(2_000)

                elements: List[Dict] = page.evaluate(self._JS_EXTRACT)
                return {
                    "status": "ok",
                    "url": page.url,
                    "title": page.title(),
                    "elements": elements,
                }
            except Exception as exc:
                return {"status": "error", "url": url, "error": str(exc)}
            finally:
                browser.close()

    def _looks_like_login_page(self, url: str, page: Any = None) -> bool:
        """Return True if the URL hints at login OR the page has a password input."""
        url_hint = any(kw in url.lower() for kw in ("login", "signin", "sign-in", "auth"))
        if url_hint:
            return True
        # DOM-based detection: password field present on ANY site
        if page is not None:
            try:
                return page.locator("input[type=password]").count() > 0
            except Exception:
                pass
        return False

    def _try_login(self, page: Any, creds: Dict) -> None:
        username = creds.get("username", "")
        password = creds.get("password", "")

        # Username field — broadest possible cascade
        for sel in (
            "[data-test='username']", "[data-testid='username']",
            "#username", "#user", "#email", "#login",
            "input[name='username']", "input[name='user']",
            "input[name='email']", "input[name='login']",
            "input[autocomplete='username']", "input[autocomplete='email']",
            "input[type='email']",
            "[placeholder*='username' i]", "[placeholder*='email' i]",
            "[placeholder*='user name' i]", "[placeholder*='login' i]",
            "input[type='text']:first-of-type",
        ):
            try:
                if page.locator(sel).count() > 0:
                    page.locator(sel).first.fill(username)
                    break
            except Exception:
                continue

        # Password field — broadest possible cascade
        for sel in (
            "[data-test='password']", "[data-testid='password']",
            "#password", "#pass", "#passwd",
            "input[name='password']", "input[name='pass']", "input[name='passwd']",
            "input[autocomplete='current-password']", "input[autocomplete='password']",
            "input[type='password']",
            "[placeholder*='password' i]", "[placeholder*='pass' i]",
        ):
            try:
                if page.locator(sel).count() > 0:
                    page.locator(sel).first.fill(password)
                    break
            except Exception:
                continue

        # Submit button — broadest possible cascade
        for sel in (
            "[data-test='login-button']", "[data-testid='login-button']",
            "[data-test='submit']", "[data-testid='submit']",
            "button[type='submit']", "input[type='submit']",
            "button:has-text('Login')", "button:has-text('Log In')",
            "button:has-text('Sign In')", "button:has-text('Sign in')",
            "button:has-text('Submit')", "button:has-text('Continue')",
            "[role='button']:has-text('Login')", "[role='button']:has-text('Sign In')",
        ):
            try:
                if page.locator(sel).count() > 0:
                    page.locator(sel).first.click()
                    break
            except Exception:
                continue


# ── Auto DOM Mapper ───────────────────────────────────────────────────────────

class AutoDOMMapper:
    """Map story step descriptions to real DOM selectors by probing the live app.

    Used exclusively by `framework build` — zero AI tokens.
    Each page is probed once; results are cached for the duration of the build.
    """

    _STOP_WORDS = {
        "a", "an", "the", "my", "your", "our", "with", "and", "or", "to", "for",
        "in", "on", "of", "is", "are", "as", "user", "i", "want", "be", "able",
        "should", "can", "do", "does", "have", "has", "get", "then", "after",
        "before", "when", "that", "this", "it", "they", "their", "its",
    }

    _PATH_HINTS: Dict[str, str] = {
        "login": "/login", "sign in": "/login", "signin": "/login",
        "register": "/register", "signup": "/signup", "sign up": "/signup",
        "dashboard": "/dashboard", "home": "/", "main": "/",
        "profile": "/profile", "account": "/account", "settings": "/settings",
        "users": "/users", "admin": "/admin", "checkout": "/checkout",
        "cart": "/cart", "products": "/products", "items": "/items",
        "orders": "/orders", "reports": "/reports",
    }

    # Generic keywords that suggest a click may trigger a page navigation.
    # These are intentionally application-agnostic.
    _NAV_TRIGGER_KEYWORDS = (
        "login", "log in", "sign in", "signin", "submit", "continue",
        "next", "proceed", "confirm", "finish", "save", "create",
    )

    def __init__(self, base_url: str, credentials: Dict | None = None) -> None:
        self.base_url = base_url.rstrip("/")
        self.credentials = credentials
        self._prober = DOMProber()
        self._cache: Dict[str, List[Dict]] = {}

    def enrich_story(self, story: Dict[str, Any]) -> Dict[str, Any]:
        """Return a copy of the story with all TODO selectors replaced by real ones."""
        import copy
        enriched = copy.deepcopy(story)
        current_url = self.base_url
        # When True the next probe must re-probe (navigation may have occurred)
        _invalidate_next = False

        for step in enriched.get("steps", []):
            action = step.get("action", "")
            target = step.get("target", "")
            description = step.get("description", "")

            if action == "navigate":
                path = self._resolve_path(target, description)
                step["target"] = path
                current_url = self.base_url + path
                _invalidate_next = False
                continue

            if action == "assert_url":
                if not target or "TODO" in target:
                    step["target"] = self._resolve_path("", description)
                continue

            if "TODO" in (target or ""):
                elements, final_url = self._probe_cached(current_url, force=_invalidate_next)
                # Advance current_url if the prober landed somewhere else (e.g. post-login redirect)
                if final_url and final_url != current_url:
                    current_url = final_url
                real_selector = self._best_selector_for_step(elements, action, description, step.get("value", ""))
                step["target"] = real_selector
                _invalidate_next = False

            # After a click that looks like a form submission / navigation trigger,
            # mark that the next probe should not reuse the cached page.
            if action == "click" and self._is_nav_trigger(description):
                _invalidate_next = True

        return enriched

    def _is_nav_trigger(self, description: str) -> bool:
        """Return True when a click description suggests the page will navigate."""
        low = description.lower()
        return any(kw in low for kw in self._NAV_TRIGGER_KEYWORDS)

    def _probe_cached(self, url: str, force: bool = False) -> tuple:
        """Return (elements, final_url). Re-probes when force=True or url not cached."""
        if force or url not in self._cache:
            result = self._prober.probe(url, self.credentials)
            final_url = result.get("url") or url
            elements = result.get("elements", [])
            # Cache under the URL we actually probed
            self._cache[final_url] = elements
            # Also cache under the requested URL so future identical requests hit cache
            if final_url != url:
                self._cache[url] = elements
            return elements, final_url
        return self._cache[url], url

    def _resolve_path(self, target: str, description: str) -> str:
        if target and not target.startswith("TODO"):
            return target if target.startswith("/") else f"/{target}"
        desc = description.lower()
        for hint, path in self._PATH_HINTS.items():
            if hint in desc:
                return path
        return "/"

    def _best_selector_for_step(self, elements: List[Dict], action: str, description: str, value: str = "") -> str:
        keywords = self._keywords(description + " " + value)
        scored = [(self._score(el, action, keywords), el) for el in elements]
        scored.sort(key=lambda x: x[0], reverse=True)

        if scored and scored[0][0] > 10:
            return self._selector_string(scored[0][1])

        kw_str = "_".join(keywords[:3]) if keywords else "element"
        return f"TODO__{action.upper()}_{kw_str.upper()}"

    def _keywords(self, text: str) -> List[str]:
        words = re.sub(r"[^a-z0-9\s]", "", text.lower()).split()
        return [w for w in words if w not in self._STOP_WORDS and len(w) > 2]

    def _score(self, el: Dict, action: str, keywords: List[str]) -> int:
        score = 0
        checks = [
            ("dataTest",    100),
            ("ariaLabel",   80),
            ("id",          70),
            ("placeholder", 65),
            ("name",        60),
            ("text",        45),
            ("href",        30),
            ("className",   15),
        ]
        for attr, weight in checks:
            val = (el.get(attr) or "").lower()
            if any(kw in val for kw in keywords):
                score += weight

        tag = (el.get("tag") or "")
        el_type = (el.get("type") or "").lower()

        if action == "fill":
            if tag == "input" and el_type not in ("submit", "button", "checkbox", "radio", "hidden"):
                score += 30
            if tag == "textarea":
                score += 25
        elif action == "click":
            if tag in ("button", "a"):
                score += 25
        elif action == "select":
            if tag == "select":
                score += 40

        # Penalise hidden/submit inputs for fill actions
        if tag == "input" and el_type in ("hidden", "submit") and action == "fill":
            score -= 60

        return score

    def _selector_string(self, el: Dict) -> str:
        # Use the exact attribute name that was present on the element
        if el.get("dataTest"):
            attr = el.get("dataTestAttr") or "data-test"
            return f"[{attr}='{el['dataTest']}']"
        if el.get("id"):
            return f"#{el['id']}"
        if el.get("ariaLabel"):
            return f"[aria-label='{el['ariaLabel']}']"
        if el.get("name") and el.get("tag") in ("input", "select", "textarea"):
            return f"{el['tag']}[name='{el['name']}']"
        if el.get("text") and el.get("tag") in ("button", "a"):
            text = el["text"].replace("'", "\\'")[:40]
            return f"{el['tag']}:has-text('{text}')"
        if el.get("placeholder"):
            return f"[placeholder='{el['placeholder']}']"
        return f"TODO__{el.get('tag', 'element')}"


# ── Enhanced CodeGenerator (with Allure support) ──────────────────────────────

class AllureTestGenerator:
    """Generates pytest test files with Allure decorators from enriched story dicts.

    Separate from CodeGenerator to keep concerns clean.
    Always uses the enriched story (real selectors from AutoDOMMapper).
    """

    def generate(self, story: Dict[str, Any], project_name: str) -> str:
        story_id = story.get("id", "generated")
        title = story.get("title", "Generated Test")
        description = story.get("description", "")
        steps = story.get("steps", [])
        tags = story.get("tags", [])
        negatives = story.get("negative_scenarios", [])
        actor = story.get("actor", "user")
        ts = _timestamp()

        class_name = _to_class_name(story_id)
        marks = "".join(f"@pytest.mark.{t}\n" for t in tags)
        allure_feature = title.split("—")[0].strip() if "—" in title else title
        allure_story = title.split("—")[1].strip() if "—" in title else ""

        lines: List[str] = [
            f'"""',
            f"AI Automation Framework — Generated Test",
            f"Story   : {title}",
            f"ID      : {story_id}",
            f"Actor   : {actor}",
            f"Created : {ts}",
            f'"""',
            "from __future__ import annotations",
            "",
            "import os",
            "",
            "import pytest",
            "import allure",
            "from playwright.sync_api import Page",
            "",
            "",
            f'@allure.feature("{allure_feature}")',
        ]
        if allure_story:
            lines.append(f'@allure.story("{allure_story}")')
        lines += [
            f'@allure.severity(allure.severity_level.CRITICAL)',
            f"class Test{class_name}:",
            f'    """{description}"""',
            "",
        ]

        # Happy path test
        for tag in tags:
            lines.append(f"    @pytest.mark.{tag}")
        lines.append(f"    @allure.title('Happy path — {title[:60]}')")
        lines.append(f"    def test_happy_path(self, page: Page, base_url: str, memory) -> None:")
        lines.append(f'        """Happy path for: {title}"""')

        for step in steps:
            code = self._step_to_code(step)
            lines.append(f"        {code}")

        lines.append("")

        # Negative scenarios
        for neg in negatives:
            name = _slug(neg.get("title", "scenario"))
            expected = neg.get("expected", "")
            lines += [
                f"    @allure.title('{neg.get('title', 'Negative scenario')}')",
                f"    @allure.severity(allure.severity_level.NORMAL)",
                f"    def test_{name}(self, page: Page, base_url: str, memory) -> None:",
                f'        """{neg.get("title", "")}',
                "",
                f"        Expected: {expected}",
                '        """',
                "        # TODO: implement negative scenario steps",
                "        pass",
                "",
            ]

        return "\n".join(lines)

    def _step_to_code(self, step: Dict) -> str:
        action = step.get("action", "")
        target = step.get("target", "")
        value = step.get("value", "")
        desc = step.get("description", "")
        comment = f"  # {desc}" if desc else ""

        if action == "navigate":
            # base_url is a pytest fixture injected via conftest.py
            return f'page.goto(base_url + "{target}"){comment}'
        if action == "fill":
            val_expr = self._value_expr(value)
            return f'page.fill("{target}", {val_expr}){comment}'
        if action == "click":
            return f'page.click("{target}"){comment}'
        if action == "assert_url":
            return f'page.wait_for_url("**{target}"){comment}'
        if action == "assert_visible":
            return f'assert page.locator("{target}").is_visible(){comment}'
        if action == "assert_text":
            return f'assert "{value}" in page.locator("{target}").inner_text(){comment}'
        if action == "select":
            return f'page.select_option("{target}", "{value}"){comment}'
        return f'pytest.fail("Unsupported action {action!r} — story step not implemented (target: {target!r})"){comment}'

    @staticmethod
    def _value_expr(value: str) -> str:
        """Return a Python expression string for a fill value.

        Credential placeholders are resolved from environment variables at
        test runtime so the generated file never contains hardcoded credentials.
        """
        if not value or value.startswith("TODO_USERNAME"):
            return 'os.getenv("FRAMEWORK_USERNAME", "")'
        if value.startswith("TODO_PASSWORD"):
            return 'os.getenv("FRAMEWORK_PASSWORD", "")'
        if value.startswith("TODO_"):
            return f'""  # TODO: provide value for {value}'
        return f'"{value}"'


# ── Project Scaffolder ────────────────────────────────────────────────────────

class ProjectScaffolder:
    """Scaffold a complete test project skeleton for a new target application.

    Generated files are listed in .gitignore — the framework repo stays
    application-agnostic.  Each client adapts the skeleton to their app's DOM/API.

    Usage:
        scaffolder = ProjectScaffolder("https://myapp.com", "myapp", "both")
        scaffolder.scaffold()
    """

    def __init__(self, url: str, name: str, project_type: str = "both") -> None:
        self.url = url.rstrip("/")
        self.name = re.sub(r"[\s\-]+", "_", name.strip().lower())
        self.project_type = project_type
        self.class_name = "".join(w.capitalize() for w in self.name.split("_") if w)

    def scaffold(self) -> list[str]:
        created: list[str] = []
        if self.project_type in ("web", "both"):
            created += self._scaffold_web()
        if self.project_type in ("api", "both"):
            created += self._scaffold_api()
        return created

    # ── Web skeleton ──────────────────────────────────────────────────────────

    def _scaffold_web(self) -> list[str]:
        created = []
        locators_path = Path("locators") / f"{self.name}_locators.py"
        page_path = Path("pages") / f"{self.name}_page.py"
        story_path = Path("stories") / f"{self.name}_story.json"
        test_path = Path("tests") / "workflows" / f"test_{self.name}.py"

        for p in (locators_path, page_path, test_path):
            p.parent.mkdir(parents=True, exist_ok=True)
        story_path.parent.mkdir(parents=True, exist_ok=True)

        if not locators_path.exists():
            locators_path.write_text(self._locators_source(), encoding="utf-8")
            created.append(str(locators_path))

        if not page_path.exists():
            page_path.write_text(self._page_source(), encoding="utf-8")
            created.append(str(page_path))

        if not story_path.exists():
            story_path.write_text(self._web_story_json(), encoding="utf-8")
            created.append(str(story_path))

        if not test_path.exists():
            test_path.write_text(self._web_test_source(), encoding="utf-8")
            created.append(str(test_path))

        return created

    def _locators_source(self) -> str:
        ts = _timestamp()
        cn = self.class_name
        return f'''\
"""
Generated by AI Automation Framework  |  {ts}
Locators for: {cn}

HOW TO UPDATE
  1. Open the target URL in a browser with DevTools (F12)
  2. For each TODO selector below, inspect the real element and replace the placeholder
  3. Prefer [data-test='…'] > #id > .css-class > xpath
  4. Or run: framework inspect --url {self.url}  (requires MCP server)
"""


class {cn}Locators:
    """CSS/attribute selectors for {cn}. All TODOs must be resolved before tests run."""

    # ── Page load indicator (visible only when the page is fully rendered) ─────
    PAGE_INDICATOR: str = "main, [role=\\'main\\'], .main-content"  # TODO: update

    # ── Login form ────────────────────────────────────────────────────────────
    USERNAME_FIELD: str = "[data-test=\\'username\\']"      # TODO: update
    PASSWORD_FIELD: str = "[data-test=\\'password\\']"      # TODO: update
    LOGIN_BUTTON: str = "[data-test=\\'login-button\\']"    # TODO: update
    LOGIN_ERROR: str = "[data-test=\\'error\\']"            # TODO: update

    # ── Post-login dashboard (visible after successful authentication) ─────────
    DASHBOARD_HEADING: str = "h1, .dashboard-title"         # TODO: update
    USER_MENU: str = ".user-menu, [aria-label=\\'user menu\\']"  # TODO: update
    LOGOUT_LINK: str = "[data-test=\\'logout\\'], .logout"  # TODO: update
'''

    def _page_source(self) -> str:
        ts = _timestamp()
        cn = self.class_name
        sn = self.name
        url = self.url
        return f'''\
"""
Generated by AI Automation Framework  |  {ts}
Page Object for: {cn}
Target URL     : {url}
"""
from __future__ import annotations

from playwright.sync_api import Page

from core.base_page import BasePage
from locators.{sn}_locators import {cn}Locators


class {cn}Page(BasePage):
    """Page Object for {cn}. Extend with methods specific to your application."""

    LOGIN_PATH: str = "/"
    DASHBOARD_PATH: str = "/dashboard"  # TODO: update

    def __init__(self, page: Page, base_url: str = "{url}") -> None:
        super().__init__(page, base_url)

    # ── Navigation ────────────────────────────────────────────────────────────

    def navigate_to(self) -> None:
        self.navigate(self.LOGIN_PATH)

    def is_loaded(self) -> bool:
        return self.is_visible({cn}Locators.PAGE_INDICATOR)

    # ── Authentication ────────────────────────────────────────────────────────

    def login(self, username: str, password: str) -> None:
        self.fill({cn}Locators.USERNAME_FIELD, username)
        self.fill({cn}Locators.PASSWORD_FIELD, password)
        self.click({cn}Locators.LOGIN_BUTTON)

    def is_error_visible(self) -> bool:
        return self.is_visible({cn}Locators.LOGIN_ERROR)

    def get_error_message(self) -> str:
        return self.get_text({cn}Locators.LOGIN_ERROR)

    def is_logged_in(self) -> bool:
        return self.is_visible({cn}Locators.DASHBOARD_HEADING)

    def logout(self) -> None:
        self.click({cn}Locators.LOGOUT_LINK)
'''

    def _web_story_json(self) -> str:
        import json
        story = {
            "id": f"{self.name}_login_001",
            "title": f"{self.class_name} User Login",
            "description": f"As a user I want to log in to {self.class_name} so I can access the application.",
            "priority": "critical",
            "tags": ["authentication", "smoke"],
            "base_url": self.url,
            "pages": [f"{self.class_name}Page"],
            "preconditions": [f"Browser is open at {self.url}"],
            "steps": [
                {"id": "step_01", "action": "navigate", "target": "/", "description": "Open login page"},
                {"id": "step_02", "action": "fill", "target": "TODO_USERNAME_SELECTOR", "value": "TODO_USERNAME", "description": "Enter username"},
                {"id": "step_03", "action": "fill", "target": "TODO_PASSWORD_SELECTOR", "value": "TODO_PASSWORD", "description": "Enter password"},
                {"id": "step_04", "action": "click", "target": "TODO_LOGIN_BUTTON_SELECTOR", "description": "Click login"},
                {"id": "step_05", "action": "assert_url", "target": "TODO__POST_LOGIN_PATH", "description": "Verify redirect after login — update target path for your app"}
            ],
            "expected_outcomes": [
                "User is redirected to dashboard",
                "No error message is shown"
            ],
            "negative_scenarios": [
                {
                    "id": "neg_01",
                    "title": "Empty credentials show validation error",
                    "steps": ["Leave fields empty", "Click login"],
                    "expected": "Validation error is visible"
                },
                {
                    "id": "neg_02",
                    "title": "Wrong credentials show auth error",
                    "steps": ["Enter wrong credentials", "Click login"],
                    "expected": "Auth error, user stays on login page"
                }
            ]
        }
        return json.dumps(story, indent=2) + "\n"

    def _web_test_source(self) -> str:
        ts = _timestamp()
        cn = self.class_name
        sn = self.name
        url = self.url
        return f'''\
"""
Generated by AI Automation Framework  |  {ts}
Test suite for: {cn}
Target URL    : {url}

HOW TO COMPLETE THIS SKELETON
  1. Update locators in locators/{sn}_locators.py with real selectors
  2. Set credentials in .env: {cn.upper()}_USERNAME / {cn.upper()}_PASSWORD
  3. The base_url fixture reads from config.json — run 'framework setup' to set it
  4. Add more test classes (inventory, checkout, …) following this pattern
"""
from __future__ import annotations

import os

import pytest
from playwright.sync_api import Page

from pages.{sn}_page import {cn}Page

# Credentials loaded from .env — never hardcode
VALID_USER = os.getenv("{cn.upper()}_USERNAME", "")
VALID_PASS = os.getenv("{cn.upper()}_PASSWORD", "")


@pytest.mark.authentication
@pytest.mark.smoke
class Test{cn}Login:
    """Login flows: happy path + common negative scenarios."""

    def test_login_page_loads(self, page: Page, base_url: str, memory) -> None:
        app = {cn}Page(page, base_url)
        app.navigate_to()
        assert app.is_loaded(), "Login page not visible"

    def test_valid_login_redirects(self, page: Page, base_url: str, memory) -> None:
        app = {cn}Page(page, base_url)
        app.navigate_to()
        app.login(VALID_USER, VALID_PASS)
        assert app.is_logged_in(), "Dashboard not visible after login"
        assert not app.is_error_visible(), "Unexpected error after valid login"

    def test_empty_credentials_show_error(self, page: Page, base_url: str, memory) -> None:
        app = {cn}Page(page, base_url)
        app.navigate_to()
        app.login("", "")
        assert app.is_error_visible(), "Expected validation error for empty credentials"

    def test_wrong_password_shows_error(self, page: Page, base_url: str, memory) -> None:
        app = {cn}Page(page, base_url)
        app.navigate_to()
        app.login(VALID_USER, "definitely_wrong_password")
        assert app.is_error_visible(), "Expected auth error for wrong password"
        assert not app.is_logged_in(), "Should not be logged in with wrong password"
'''

    # ── API skeleton ──────────────────────────────────────────────────────────

    def _scaffold_api(self) -> list[str]:
        created = []
        story_path = Path("stories") / f"{self.name}_api_story.json"
        test_path = Path("tests") / "api" / f"test_{self.name}_api.py"

        story_path.parent.mkdir(parents=True, exist_ok=True)
        test_path.parent.mkdir(parents=True, exist_ok=True)

        if not story_path.exists():
            story_path.write_text(self._api_story_json(), encoding="utf-8")
            created.append(str(story_path))

        if not test_path.exists():
            test_path.write_text(self._api_test_source(), encoding="utf-8")
            created.append(str(test_path))

        return created

    def _api_story_json(self) -> str:
        import json
        story = {
            "id": f"{self.name}_api_001",
            "title": f"{self.class_name} API Availability",
            "description": f"HTTP-level health checks for {self.url}",
            "base_url": self.url,
            "tags": ["api", "smoke"],
            "endpoints": [
                {
                    "id": "root_returns_200",
                    "method": "GET",
                    "path": "/",
                    "description": "Root endpoint returns 200",
                    "expected_status": 200
                }
            ],
            "negative_scenarios": [
                {
                    "id": "neg_01",
                    "title": "Nonexistent path returns 404",
                    "method": "GET",
                    "path": "/nonexistent_path_xyz",
                    "expected_status": 404,
                    "expected": "404 Not Found"
                }
            ]
        }
        return json.dumps(story, indent=2) + "\n"


    def _api_test_source(self) -> str:
        ts = _timestamp()
        cn = self.class_name
        url = self.url
        header = f'''"""
Generated by AI Automation Framework  |  {ts}
API Test suite for: {cn}  —  Target: {url}
"""'''
        body = f'''
from __future__ import annotations
import pytest
from services.api_service import APIService


@pytest.mark.api
class Test{cn}Api:
    """API smoke tests for {cn}."""

    def test_health_check(self, api_client: APIService) -> None:
        """Verify the API is reachable."""
        resp = api_client.get("/")
        resp.assert_ok()

    # TODO: add endpoint tests below
    # def test_list_items(self, api_client: APIService) -> None:
    #     resp = api_client.get("/items")
    #     resp.assert_ok()
'''
        return header + body


# ── Module-level helpers ─────────────────────────────────────────────────────

def _timestamp() -> str:
    return datetime.now().strftime("%Y-%m-%dT%H:%M:%S")


def _url_path(url: str) -> str:
    from urllib.parse import urlparse
    path = urlparse(url).path
    return path if path else "/"


def _camel_to_snake(name: str) -> str:
    s = re.sub(r"(.)([A-Z][a-z]+)", r"\1_\2", name)
    return re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", s).lower()


def _to_class_name(story_id: str) -> str:
    return "".join(w.capitalize() for w in re.split(r"[\W_]+", story_id) if w)


def _slug(text: str) -> str:
    return re.sub(r"[^a-z0-9]+", "_", text.lower()).strip("_")[:50]


def _action_to_code(action: str, target: str, value: str, desc: str) -> str:
    comment = f"  # {desc}" if desc else ""
    if action == "navigate":
        return f'page.goto(base_url + "{target}"){comment}'
    if action == "fill":
        return f'page.fill("{target}", "{value}"){comment}'
    if action == "click":
        return f'page.click("{target}"){comment}'
    if action == "assert_url":
        return f'page.wait_for_url("**{target}"){comment}'
    if action == "assert_visible":
        return f'assert page.locator("{target}").is_visible(){comment}'
    if action == "assert_text":
        return f'assert "{value}" in page.locator("{target}").inner_text(){comment}'
    if action == "select":
        return f'page.select_option("{target}", "{value}"){comment}'
    action_r = repr(action)
    return f'pytest.fail("Unsupported action {action_r}"){comment}'


def _infer_action(desc: str) -> str:
    low = desc.lower()
    if any(w in low for w in ("click", "press", "tap", "submit", "select")):
        return "click"
    if any(w in low for w in ("type", "enter", "fill", "input", "write")):
        return "fill"
    if any(w in low for w in ("navigate", "go to", "open", "visit", "load")):
        return "navigate"
    if any(w in low for w in ("url", "redirect", "location", "route")):
        return "assert_url"
    if any(w in low for w in ("see", "verify", "check", "assert", "visible", "shown")):
        return "assert_visible"
    return "assert_visible"
